### ISSUE TITLE
Moveing variable creation to a .c file

### ISSUE THREAD

**Issue by daltonfury42** [arun-Joseph/xsm_expl#1]
https://github.com/arun-Joseph/xsm_expl/blob/c9c62f7b5764f49ac8d662077ae91e9eb27744c0/xsm_dev/machine.h#L138

What the people have followed is to define structures in .h files, and then declare variables only in the .c file. So I suggest you move the above line to machine.c. Just a better programming practice. :)

**Comment by arun-joseph** [comment]
I moved the declaration to machine.c file.
