### ISSUE TITLE
Possible Double Counting

### ISSUE THREAD

**Issue by daltonfury42** [arun-Joseph/xsm_expl#2]
https://github.com/arun-Joseph/xsm_expl/blob/c9c62f7b5764f49ac8d662077ae91e9eb27744c0/xsm_dev/machine.c#L750
I think you are also counting once inside the machine_get_address_int function which is invoked a few lines earlier. Can you check?

**Comment by daltonfury42** [comment]
Maybe the increment at #819 is not required?

**Comment by arun-joseph** [comment]
It is added so that MOV [LOC], Ri and MOV Ri, [LOC] are counted as 2 memory fetch and 1 instruction fetch.
