### ISSUE TITLE
Instruction count not incremented.

### ISSUE THREAD

**Issue by daltonfury42** [arun-Joseph/xsm_expl#3]
https://github.com/arun-Joseph/xsm_expl/blob/c9c62f7b5764f49ac8d662077ae91e9eb27744c0/xsm_dev/machine.c#L864

**Comment by arun-joseph** [comment]
I moved the machine_execute_instruction(). So, now all user privileged will be counted as 1 instruction fetch. Should any instruction be counted as 2 instruction fetch?
